[project]
name = "lockcell"
version = "0.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "graphviz>=0.21",
    "numpy>=2.2.6",
    "pymonik",
]

[tool.uv.sources]
pymonik = { path = "../PymoniK/pymonik" }
