name: Code Integration

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Check linting, formatting and typing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "lockcell/.python-version"

      - name: Linting
        run: cd lockcell && uv run ruff check ..

      - name: Formatting
        run: cd lockcell && uv run ruff format ..

      - name: Check Diff
        run: |
          DIFF="$(git diff --name-only)"

          if [ -z "$DIFF" ]; then
            echo "OK: Format is clean"
          else
            echo "Error: Format was not clean"
            echo "List of files:"
            echo "$DIFF"
            git diff
            exit 1
          fi